apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: wh
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: woohek00/linux-master-app:1.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits: 
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: DB_USER # 파이썬 코드에서 읽을 이름
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: DB_PASSWORD
