apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-wh
  namespace: wh
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "1"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-dh
  namespace: dh
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "1"
    limits.memory: 2Gi